"""change_telegram_id_to_bigint

Revision ID: 7fd2cb94f886
Revises: e9944cd10cc4
Create Date: 2026-04-09 22:03:28.492784
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "7fd2cb94f886"
down_revision: Union[str, None] = "e9944cd10cc4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Change telegram_id from INTEGER to BIGINT to support large Telegram IDs
    op.alter_column(
        "users",
        "telegram_id",
        existing_type=sa.Integer(),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mood_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("mood", sa.String(length=30), nullable=False),
        sa.Column("energy_level", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_mood_log_user_date", "mood_log", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "step_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("steps", sa.Integer(), nullable=False),
        sa.Column("distance_km", sa.Float(), nullable=True),
        sa.Column("calories_burned", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_step_log_user_date", "step_log", ["user_id", "created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_step_log_user_date", table_name="step_log")
    op.drop_table("step_log")
    op.drop_index("idx_mood_log_user_date", table_name="mood_log")
    op.drop_table("mood_log")
    # ### end Alembic commands ###

    # Revert telegram_id back to INTEGER
    op.alter_column(
        "users",
        "telegram_id",
        existing_type=sa.BigInteger(),
        type_=sa.Integer(),
        existing_nullable=False,
    )
