"""add_mood_log_step_log_tables

Revision ID: e9944cd10cc4
Revises: 57366e7a9982
Create Date: 2026-04-09 21:22:08.075600
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'e9944cd10cc4'
down_revision: Union[str, None] = '57366e7a9982'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
